USE master; 
GO 
CREATE DATABASE Manchaster_Energy_Performance

CREATE VIEW Manchester_Current_Energy1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([CURRENT_ENERGY_RATING], ''), 'NA') AS [CURRENT_ENERGY_RATING],
    COALESCE(NULLIF([CURRENT_ENERGY_EFFICIENCY], ''), 'NA') AS [CURRENT_ENERGY_EFFICIENCY],
    COALESCE(NULLIF([ENVIRONMENT_IMPACT_CURRENT], ''), 'NA') AS [ENVIRONMENT_IMPACT_CURRENT],
    COALESCE(NULLIF([ENERGY_CONSUMPTION_CURRENT], ''), 'NA') AS [ENERGY_CONSUMPTION_CURRENT],
    COALESCE(NULLIF([CO2_EMISSIONS_CURRENT], ''), 'NA') AS [CO2_EMISSIONS_CURRENT],
    COALESCE(NULLIF([CO2_EMISS_CURR_PER_FLOOR_AREA], ''), 'NA') AS [CO2_EMISS_CURR_PER_FLOOR_AREA],
    COALESCE(NULLIF([LIGHTING_COST_CURRENT], ''), 'NA') AS [LIGHTING_COST_CURRENT],
    COALESCE(NULLIF([HEATING_COST_CURRENT], ''), 'NA') AS [HEATING_COST_CURRENT],
    COALESCE(NULLIF([HOT_WATER_COST_CURRENT], ''), 'NA') AS [HOT_WATER_COST_CURRENT]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

CREATE VIEW Manchester_Potential_Energy1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([POTENTIAL_ENERGY_RATING], ''), 'NA') AS [POTENTIAL_ENERGY_RATING],
    COALESCE(NULLIF([POTENTIAL_ENERGY_EFFICIENCY], ''), 'NA') AS [POTENTIAL_ENERGY_EFFICIENCY],
    COALESCE(NULLIF([ENVIRONMENT_IMPACT_POTENTIAL], ''), 'NA') AS [ENVIRONMENT_IMPACT_POTENTIAL],
    COALESCE(NULLIF([ENERGY_CONSUMPTION_POTENTIAL], ''), 'NA') AS [ENERGY_CONSUMPTION_POTENTIAL],
    COALESCE(NULLIF([CO2_EMISSIONS_POTENTIAL], ''), 'NA') AS [CO2_EMISSIONS_POTENTIAL],
    COALESCE(NULLIF([LIGHTING_COST_POTENTIAL], ''), 'NA') AS [LIGHTING_COST_POTENTIAL],
    COALESCE(NULLIF([HEATING_COST_POTENTIAL], ''), 'NA') AS [HEATING_COST_POTENTIAL],
    COALESCE(NULLIF([HOT_WATER_COST_POTENTIAL], ''), 'NA') AS [HOT_WATER_COST_POTENTIAL]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

CREATE VIEW Energy_Efficiency_Rating1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([ENERGY_CONSUMPTION_CURRENT], ''), 'NA') AS [ENERGY_CONSUMPTION_CURRENT],
    COALESCE(NULLIF([ENERGY_CONSUMPTION_POTENTIAL], ''), 'NA') AS [ENERGY_CONSUMPTION_POTENTIAL],
    COALESCE(NULLIF([HOT_WATER_ENERGY_EFF], ''), 'NA') AS [HOT_WATER_ENERGY_EFF],
    COALESCE(NULLIF([FLOOR_ENERGY_EFF], ''), 'NA') AS [FLOOR_ENERGY_EFF],
    COALESCE(NULLIF([WINDOWS_ENERGY_EFF], ''), 'NA') AS [WINDOWS_ENERGY_EFF], 
    COALESCE(NULLIF([WALLS_ENERGY_EFF], ''), 'NA') AS [WALLS_ENERGY_EFF],
    COALESCE(NULLIF([SHEATING_ENERGY_EFF], ''), 'NA') AS [SHEATING_ENERGY_EFF],
    COALESCE(NULLIF([ROOF_ENERGY_EFF], ''), 'NA') AS [ROOF_ENERGY_EFF],
    COALESCE(NULLIF([MAINHEAT_ENERGY_EFF], ''), 'NA') AS [MAINHEAT_ENERGY_EFF],
    COALESCE(NULLIF([MAINHEATC_ENERGY_EFF], ''), 'NA') AS [MAINHEATC_ENERGY_EFF]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

CREATE VIEW Environmental_Efficiency_Rating1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([ENVIRONMENT_IMPACT_CURRENT], ''), 'NA') AS [ENVIRONMENT_IMPACT_CURRENT],
    COALESCE(NULLIF([ENVIRONMENT_IMPACT_POTENTIAL], ''), 'NA') AS [ENVIRONMENT_IMPACT_POTENTIAL],    
    COALESCE(NULLIF([HOT_WATER_ENV_EFF], ''), 'NA') AS [HOT_WATER_ENV_EFF],
    COALESCE(NULLIF([FLOOR_ENV_EFF], ''), 'NA') AS [FLOOR_ENV_EFF],
    COALESCE(NULLIF([WINDOWS_ENV_EFF], ''), 'NA') AS [WINDOWS_ENV_EFF],
    COALESCE(NULLIF([WALLS_ENV_EFF], ''), 'NA') AS [WALLS_ENV_EFF],
    COALESCE(NULLIF([SHEATING_ENV_EFF], ''), 'NA') AS [SHEATING_ENV_EFF],
    COALESCE(NULLIF([ROOF_ENV_EFF], ''), 'NA') AS [ROOF_ENV_EFF],
    COALESCE(NULLIF([MAINHEAT_ENV_EFF], ''), 'NA') AS [MAINHEAT_ENV_EFF],
    COALESCE(NULLIF([MAINHEATC_ENV_EFF], ''), 'NA') AS [MAINHEATC_ENV_EFF]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

CREATE VIEW Building_Location1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([POSTCODE], ''), 'NA') AS [POSTCODE],
    COALESCE(NULLIF([BUILDING_REFERENCE_NUMBER], ''), 'NA') AS [BUILDING_REFERENCE_NUMBER],
    COALESCE(NULLIF([PROPERTY_TYPE], ''), 'NA') AS [PROPERTY_TYPE],
    COALESCE(NULLIF([BUILT_FORM], ''), 'NA') AS [BUILT_FORM],
    COALESCE(NULLIF([INSPECTION_DATE], ''), 'NA') AS [INSPECTION_DATE],
    COALESCE(NULLIF([LOCAL_AUTHORITY], ''), 'NA') AS [LOCAL_AUTHORITY],
    COALESCE(NULLIF([LODGEMENT_DATE], ''), 'NA') AS [LODGEMENT_DATE],
    COALESCE(NULLIF([TRANSACTION_TYPE], ''), 'NA') AS [TRANSACTION_TYPE],
    COALESCE(NULLIF([CONSTITUENCY], ''), 'NA') AS [CONSTITUENCY],
    COALESCE(NULLIF([ADDRESS], ''), 'NA') AS [ADDRESS],
    COALESCE(NULLIF([LOCAL_AUTHORITY_LABEL], ''), 'NA') AS [LOCAL_AUTHORITY_LABEL],
    COALESCE(NULLIF([CONSTITUENCY_LABEL], ''), 'NA') AS [CONSTITUENCY_LABEL],
    COALESCE(NULLIF([POSTTOWN], ''), 'NA') AS [POSTTOWN],
    COALESCE(NULLIF([CONSTRUCTION_AGE_BAND], ''), 'NA') AS [CONSTRUCTION_AGE_BAND],
    COALESCE(NULLIF([LODGEMENT_DATETIME], ''), 'NA') AS [LODGEMENT_DATETIME],
    COALESCE(NULLIF([TENURE], ''), 'NA') AS [TENURE],
    COALESCE(NULLIF([UPRN], ''), 'NA') AS [UPRN],
    COALESCE(NULLIF([UPRN_SOURCE], ''), 'NA') AS [UPRN_SOURCE]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

CREATE VIEW Building_Energy1 AS
SELECT     -- Selecting the necessary columns needed for the analysis
    COALESCE(NULLIF([LMK_KEY], ''), 'NA') AS [LMK_KEY],  -- Each columns Missing values are replaced as 'NA'
    COALESCE(NULLIF([TOTAL_FLOOR_AREA], ''), 'NA') AS [TOTAL_FLOOR_AREA],
    COALESCE(NULLIF([ENERGY_TARIFF], ''), 'NA') AS [ENERGY_TARIFF],
    COALESCE(NULLIF([MAINS_GAS_FLAG], ''), 'NA') AS [MAINS_GAS_FLAG],
    COALESCE(NULLIF([FLOOR_LEVEL], ''), 'NA') AS [FLOOR_LEVEL],
    COALESCE(NULLIF([FLAT_TOP_STOREY], ''), 'NA') AS [FLAT_TOP_STOREY],
    COALESCE(NULLIF([FLAT_STOREY_COUNT], ''), 'NA') AS [FLAT_STOREY_COUNT],
    COALESCE(NULLIF([MAIN_HEATING_CONTROLS], ''), 'NA') AS [MAIN_HEATING_CONTROLS],
    COALESCE(NULLIF([MULTI_GLAZE_PROPORTION], ''), 'NA') AS [MULTI_GLAZE_PROPORTION],
    COALESCE(NULLIF([GLAZED_TYPE], ''), 'NA') AS [GLAZED_TYPE],
    COALESCE(NULLIF([GLAZED_AREA], ''), 'NA') AS [GLAZED_AREA],
    COALESCE(NULLIF([EXTENSION_COUNT], ''), 'NA') AS [EXTENSION_COUNT],
    COALESCE(NULLIF([NUMBER_HABITABLE_ROOMS], ''), 'NA') AS [NUMBER_HABITABLE_ROOMS],
    COALESCE(NULLIF([NUMBER_HEATED_ROOMS], ''), 'NA') AS [NUMBER_HEATED_ROOMS],
    COALESCE(NULLIF([LOW_ENERGY_LIGHTING], ''), 'NA') AS [LOW_ENERGY_LIGHTING],
    COALESCE(NULLIF([NUMBER_OPEN_FIREPLACES], ''), 'NA') AS [NUMBER_OPEN_FIREPLACES],
    COALESCE(NULLIF([MAIN_FUEL], ''), 'NA') AS [MAIN_FUEL],
    COALESCE(NULLIF([WIND_TURBINE_COUNT], ''), 'NA') AS [WIND_TURBINE_COUNT],
    COALESCE(NULLIF([HEAT_LOSS_CORRIDOR], ''), 'NA') AS [HEAT_LOSS_CORRIDOR],
    COALESCE(NULLIF([UNHEATED_CORRIDOR_LENGTH], ''), 'NA') AS [UNHEATED_CORRIDOR_LENGTH],
    COALESCE(NULLIF([FLOOR_HEIGHT], ''), 'NA') AS [FLOOR_HEIGHT],
    COALESCE(NULLIF([PHOTO_SUPPLY], ''), 'NA') AS [PHOTO_SUPPLY],
    COALESCE(NULLIF([SOLAR_WATER_HEATING_FLAG], ''), 'NA') AS [SOLAR_WATER_HEATING_FLAG],
    COALESCE(NULLIF([MECHANICAL_VENTILATION], ''), 'NA') AS [MECHANICAL_VENTILATION],
    COALESCE(NULLIF([FIXED_LIGHTING_OUTLETS_COUNT], ''), 'NA') AS [FIXED_LIGHTING_OUTLETS_COUNT],
    COALESCE(NULLIF([LOW_ENERGY_FIXED_LIGHT_COUNT], ''), 'NA') AS [LOW_ENERGY_FIXED_LIGHT_COUNT]
FROM [dbo].[certificates]
WHERE CONVERT(DATE, [INSPECTION_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31'
AND CONVERT(DATE, [LODGEMENT_DATE], 103) BETWEEN '2013-01-01' AND '2023-12-31';

-- Number of rows after creating the view 
SELECT COUNT(*)
FROM [dbo].[Building_Energy1]

-- Total number of records and the average energy efficiency.
SELECT 
    COUNT(*) AS TotalRecords,
    AVG(CAST([CURRENT_ENERGY_EFFICIENCY] AS FLOAT)) AS AvgEnergyEfficiency
FROM [dbo].[Manchester_Current_Energy1];

-- Ranking the records by their current energy efficiency in descending order.
SELECT 
    [POSTCODE],
    [CURRENT_ENERGY_EFFICIENCY],
    ROW_NUMBER() OVER (ORDER BY [CURRENT_ENERGY_EFFICIENCY] DESC) AS Rank
FROM [dbo].[Building_Location1],[dbo].[Manchester_Current_Energy1];

-- Calculates the length of each postcode and also returns the current date.
SELECT 
    [POSTCODE], 
    LEN([POSTCODE]) AS PostcodeLength,
    GETDATE() AS CurrentDate
FROM [dbo].[Building_Location1];


